---
- name: Use RabbitMQ.
  ini_file:
    dest:    /etc/neutron/neutron.conf
    section: DEFAULT
    option:  rpc_backend
    value:   rabbit

- name: Configure RabbitMQ access.
  ini_file:
    dest:    /etc/neutron/neutron.conf
    section: oslo_messaging_rabbit
    option:  '{{ item.key }}'
    value:   '{{ item.value }}'
  with_dict:
    rabbit_host:     '{{ rabbitmq_host }}'
    rabbit_userid:   '{{ rabbitmq_user }}'
    rabbit_password: '{{ rabbitmq_password }}'

- name: Use Keystone.
  ini_file:
    dest:    /etc/neutron/neutron.conf
    section: DEFAULT
    option:  auth_strategy
    value:   keystone

- name: Configure Keystone access.
  ini_file:
    dest:    /etc/neutron/neutron.conf
    section: keystone_authtoken
    option:  '{{ item.key }}'
    value:   '{{ item.value }}'
  with_dict:
    auth_uri:            'http://{{ keystone_host }}:5000'
    auth_url:            'http://{{ keystone_host }}:35357'
    memcached_servers:   '{{ keystone_host }}:11211'
    auth_type:           password
    project_domain_name: default
    user_domain_name:    default
    project_name:        service
    username:            neutron
    password:            '{{ keystone_password }}'

- name: Configure lock path.
  ini_file:
    dest:    /etc/neutron/neutron.conf
    section: oslo_concurrency
    option:  lock_path
    value:   /var/lib/neutron/tmp

- name: Configure Nova to use Neutron.
  register: nova_config
  ini_file:
    dest:    /etc/nova/nova.conf
    section: neutron
    option:  '{{ item.key }}'
    value:   '{{ item.value }}'
  with_dict:
    url:                          'http://{{ controller_ip_address }}:9696'
    auth_url:                     'http://{{ controller_ip_address }}:35357'
    auth_type:                    password
    project_domain_name:          default
    user_domain_name:             default
    region_name:                  '{{ region }}'
    project_name:                 service
    username:                     neutron
    password:                     '{{ keystone_password }}'
    service_metadata_proxy:       true
    metadata_proxy_shared_secret: '{{ metadata_secret }}'

- name: Restart Nova service.
  service:
    name:  openstack-nova-compute.service
    state: restarted
  when: nova_config.changed

- name: Disable VXLAN for linuxbridge agent.
  ini_file:
    dest:    /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: vxlan
    option:  enable_vxlan
    value:   false
